name: chess
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.2
  - torchvision=0.17
  - opencv-python=4.9
  - numpy=1.26
  - scipy=1.13
  - scikit-learn=1.4
  - matplotlib=3.8
  - pillow=10.3
  - pip
  - pip:
    - transformers
    - chess
    - tqdm
    - filelock==3.14.0
    - fsspec==2024.3.1
    - importlib_resources==6.4.0
    - networkx==3.2.1
    - sympy==1.12
    - typing_extensions==4.11.0
